---
title: "Courses"
editor: visual
---

My teaching experience includes:

Professor at Escuela Nacional de Estudios Superiores Morelia, Universidad Nacional Autónoma de México:

-   Landscape Cartography.
-   Geographic Information Systems II.

Professor assistant at Escuela Nacional de Estudios Superiores Morelia and Facultad de Ciencias, Universidad Nacional Autónoma de México:

-   Spatial analysis and modeling.
-   Spatial analysis tools.
-   Geographic Information Systems and Cartography.
-   Geographic Information Systems II.
-   Applies Statistics.
-   Biostatistics.

Also, I gave some basic courses to learn R and to use it to perform image processing and analysis. All the courses are in Spanish.

-   [QGIS](https://github.com/JonathanVSV/CursoQGIS)

-   Introducción a R. Datos de biodiversidad: [Repositorio del curso](https://github.com/JonathanVSV/CursoR) y [videos del curso](https://www.youtube.com/watch?v=XtCs6u-pcFw&list=PLiP4keNeUXykgBY0u67mC4mBKgcjr9Q_D).

-   [Curso básico de R](%7B%7B%20site.url%20%7D%7D%7B%7B%20site.baseurl%20%7D%7D/assets/courses/BasicoR.html)

-   [Pruebas estadísticas en R](%7B%7B%20site.url%20%7D%7D%7B%7B%20site.baseurl%20%7D%7D/assets/courses/PruebEstad.html)
