---
title: "GEE"
editor: visual
---

I made a Google Earth Manual in Spanish, which can be consulted at the following link:

* [Cómo usar Google Earth Engine y no fallar en el intento](https://publicaciones.ciga.unam.mx/index.php/ec/catalog/book/12)

The GitHub page version, as well as the complete files used to build the book, can be consulted in the following repository:

* [Manual de Google Earth Engine](https://github.com/JonathanVSV/GEE_manual)

I gave a Google Earth Engine Workshop along with Gabriel Perilla, organized by SELPER - México in July 2021. The videos of this workshop can be seen in the following YouTube link: 

* [Google Earth Engine Workshop](https://www.youtube.com/watch?v=O7jLtnEbYuI&ab_channel=SchmilblickProduction)

Also, I gave a short course on how to detect floods using Sentinel-1 data in GEE.

* [GEE floods](https://www.youtube.com/watch?v=iA5WSPLi5mA)

I made some Google Earth Engine scripts that can be used to perform cloudless annual mosaics using Landsat 4, 5, 7, and 8 surface reflectance collections, or obtain the number of cloudless observations per pixel using Sentinel-2 images or both Landsat and Sentinel.

* [CloudlessMosaics](https://github.com/JonathanVSV/MxMosaic_EE)

* [PerPixelSentinel-2Obs](https://github.com/JonathanVSV/PerPixelObsSentinel-2)

* [Landsat-Sentinel-Obs](https://github.com/JonathanVSV/Landsat-Sentinel-Obs)