---
title: "Repositories"
editor: visual
---

This page shows an overview of the public repositories in my Github/Gitlab:

* Repos to use the U-Net algorithm (i.e., deep learning algorithm) to make a land use/land cover classification [U-netR](https://github.com/JonathanVSV/U-netR) or a 3D version used to detect deforestation [UnetRDef](https://github.com/JonathanVSV/U-netRDef).

* Repo with several scripts to perform different analyses for updating some of Mexico's Natural Capital indicators (Capital Natural de México). This repo contains much of the work I did in CONABIO (Comisión Nacional para el Conocimiento y Uso de la Biodiversidad) [BiodiversidadES](https://gitlab.com/OscarGOGO/BiodiversidadES).

* Repo to model aboveground biomass (AGB) using LiDAR. Includes scripts for calculating AGB, extracting LiDAR metrics, fitting different models, making AGB predictions, and writing a manuscript using RMarkdown. [AGBLiDAR](https://github.com/JonathanVSV/AGBLiDAR).

* Repo to calculate some basic forest's structural and diversity attributes: [VegCommunity](https://github.com/JonathanVSV/VegCommunity).

* Repo to fit linear models using the forest attributes as dependent variables and image texture as independent ones: [RSModels](https://github.com/JonathanVSV/RSModels).

* Repo to extract additional parameters from the BFAST model, i.e., a method to detect disturbances from images time series (e.g., amplitude, magnitude, R2, NA percentage, stable historical period): [bfast_params_extr](https://github.com/JonathanVSV/bfast_params_extr).

* Repo that contains the files to build the GEE manual book using bookdown [GEE_manual](https://github.com/JonathanVSV/GEE_manual).

* Repo that contains the analyses used to discriminate between degraded and conserved forests [Conserved-vs-Degraded-Forest](https://github.com/JonathanVSV/Conserved-vs-Degraded-Forest).

* Repo to classify vegetation in high and intermediate productivity (using NDVI) to distinguish conserved forest from secondary/degraded [Class-HPV-Deg](https://github.com/JonathanVSV/Class-HPV-Deg). 

* Repo with a leaflet html. [Cuilala-map](https://github.com/JonathanVSV/Cuilala-map).